name: My-GitHubActions-Basics
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  My-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
      - run: echo "Hello World from Testing job"


  My-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
      - run: echo "Hello World from Deploy job"
