name: My-GitHubActions-Basics
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - master 
  
jobs:
  My-testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World from Testing Job!"
  My-deploy:
    runs-on: ubuntu-latest
    steps:
      - run : echo "Hello World from Deploy job!"
