name: Deploy-To-Ubuntu-Server
run-name: ${{ github.actor }} is deploying new changes 🚀

on: 
  push:
    branches: 
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}   
      REMOTE_USER: ${{ secrets.REMOTE_USER }}   
      TARGET_DIR: ${{ secrets.TARGET_DIR }}     
      REMOTE_PORT: ${{ secrets.REMOTE_PORT }} 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH key and known_hosts
        run: |
          set -e
          # Create ~/.ssh directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write private key (from GitHub Secrets)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Start ssh-agent and add key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key

          # Set default port if empty
          SSH_PORT="${REMOTE_PORT:-22}"

          # Add host to known_hosts (avoid interactive prompt)
          ssh-keyscan -H -p "$SSH_PORT" "$REMOTE_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          SSH_PORT="${REMOTE_PORT:-22}"
          rsync -avz --delete -e "ssh -p $SSH_PORT -i ~/.ssh/deploy_key" \
            --exclude '.git' \
            --exclude '.github' \
            ./ $REMOTE_USER@$REMOTE_HOST:$TARGET_DIR/

          # Исключаем лишние директории/файлы — настройте список под свой проект
          RSYNC_EXCLUDES=(
            --exclude='.git'
            --exclude='.github'
            --exclude='node_modules'
            --exclude='.env'
            --exclude='deploy_key'
          )

          # Выполняем rsync (рекурсивно, сжатие, сохраняем права, удаляем удалённо файлы, которых нет локально)
          rsync -avz --delete -e "ssh -p $SSH_PORT -o StrictHostKeyChecking=yes" "${RSYNC_EXCLUDES[@]}" ./ "$REMOTE_USER@$REMOTE_HOST:$TARGET_DIR"

        shell: bash







