name: Deploy-To-Ubunty-Server
#-------try untill you succeed----------
run-name: ${{ github.actor }} is deploing new changes 🚀

on: 
  push:
    branches: 
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}   
      REMOTE_USER: ${{ secrets.REMOTE_USER }}   
      TARGET_DIR: ${{ secrets.TARGET_DIR }}     
      REMOTE_PORT: ${{ secrets.REMOTE_PORT }} 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH key and known_hosts
        run: |
          set -e
          # Создаём ~/.ssh
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Записываем приватный ключ (вставляется из GitHub Secrets)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Запускаем ssh-agent и добавляем ключ
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key

          # Подставляем порт по умолчанию, если SECRET пуст
          SSH_PORT="${REMOTE_PORT}"
          if [ -z "$SSH_PORT" ]; then SSH_PORT=22; fi

          # Добавляем хост в known_hosts (не будет интерактивного запроса)
          ssh-keyscan -H -p "$SSH_PORT" "$REMOTE_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        shell: bash

      - name: Sync files to remote server (rsync)
        run: |
          set -e
          SSH_PORT="${REMOTE_PORT}"
          if [ -z "$SSH_PORT" ]; then SSH_PORT=22; fi

          # Путь на сервере должен существовать или будет создан rsync'ом (в зависимости от прав)
          echo "Deploying to $REMOTE_USER@$REMOTE_HOST:$TARGET_DIR (port $SSH_PORT)"

          # Исключаем лишние директории/файлы — настройте список под свой проект
          RSYNC_EXCLUDES=(
            --exclude='.git'
            --exclude='.github'
            --exclude='node_modules'
            --exclude='.env'
            --exclude='deploy_key'
          )

          # Выполняем rsync (рекурсивно, сжатие, сохраняем права, удаляем удалённо файлы, которых нет локально)
          rsync -avz --delete -e "ssh -p $SSH_PORT -o StrictHostKeyChecking=yes" "${RSYNC_EXCLUDES[@]}" ./ "$REMOTE_USER@$REMOTE_HOST:$TARGET_DIR"

        shell: bash







